// Link Actions
export const GET_LINKS_REQUEST = 'GET_LINKS_REQUEST';
export const GET_LINKS_SUCCESS = 'GET_LINKS_SUCCESS';
export const GET_LINKS_FAILURE = 'GET_LINKS_FAILURE';
export const ADD_LINK_SUCCESS = 'ADD_LINK_SUCCESS';
export const ADD_LINK_FAILURE = 'ADD_LINK_FAILURE';


// Authentication Actions
export const LOGGED_IN_SUCCESSFULLY = 'LOGGED_IN_SUCCESSFULLY';
export const LOGGED_IN_FAILURE = 'LOGGED_IN_FAILURE';
export const LOGGED_OUT_SUCCESSFULLY = 'LOGGED_OUT_SUCCESSFULLY';
export const LOGGED_OUT_FAILURE = 'LOGGED_OUT_FAILURE';
