
// Authentication Actions
export const LOGGED_IN_SUCCESSFULLY = 'LOGGED_IN_SUCCESSFULLY';
export const LOGGED_IN_FAILURE = 'LOGGED_IN_FAILURE';
export const LOGGED_OUT_SUCCESSFULLY = 'LOGGED_OUT_SUCCESSFULLY';
export const LOGGED_OUT_FAILURE = 'LOGGED_OUT_FAILURE';
